
module.exports = { alldropdowns: {
					roles: [{ role: "Actor", text:"Acting"}, { role: "Director", text:"Direction"}, { role: "Playwright", text:"Playwright"},
                            { role: "Lights", text:"Lighting Design"},{ role: "Sound", text:"Sound Design"},
    						{ role: "Music", text:"Music Composition"},{ role: "Dramaturgist", text:"Dramaturgy"},{ role: "Costume", text:"Costume Designing"},
                            { role: "MakeUp", text:"Make-up"},
    						{ role: "SetDesign", text:"Set Designing"},{ role: "StageManager", text:"Managing Production"}, 
                            { role: "Backstage", text:"Production/Backstage Crew"}, { role: "Trainer", text:"Training"},
                            { role: "Audience", text:"Love to watch plays"}],
    				cities: [{ city: "Bengaluru", text: "Bengaluru"}, {city: "Bhopal", text: "Bhopal"}, {city:"Chennai", text:"Chennai"}, 
                             {city: "Chandigarh", text: "Chandigarh"}, {city:"Delhi", text:"Delhi"}, {city: "Hyderabad", text: "Hyderabad"},
    						 {city: "Kolkata", text:"Kolkata"}, {city: "Mumbai", text: "Mumbai"}, {city: "Pune", text: "Pune"}, 
                             {city: "Thrissur", text: "Thrissur"}, {city: "", text:"None of the above"}],
    				citiesForPost: [{ city: "Bengaluru", text: "Bengaluru"}, {city: "Bhopal", text: "Bhopal"}, {city:"Chennai", text:"Chennai"}, 
                             {city: "Chandigarh", text: "Chandigarh"}, {city:"Delhi", text:"Delhi"}, {city: "Hyderabad", text: "Hyderabad"},
                             {city: "Kolkata", text:"Kolkata"}, {city: "Mumbai", text: "Mumbai"}, {city: "Pune", text: "Pune"}, 
                             {city: "Thrissur", text: "Thrissur"}],
    				rolesForPost: [{ role: "Actor", text:"Actor"}, { role: "Director", text:"Director"}, { role: "Playwright", text:"Playwright"},
                            { role: "Lights", text:"Lighting Designer"},{ role: "Sound", text:"Sound Designer"},  { role: "MakeUp", text:"Make-up artist"},
                            { role: "Music", text:"Music Composer"},{ role: "Dramaturgist", text:"Dramaturgist"}, { role: "Costume", text:"Costume Designer"},
                            { role: "SetDesign", text:"Set Designer"},{ role: "StageManager", text:"Production Manager"}, 
                            { role: "Backstage", text:"Backstage Support"}, { role: "Trainer", text:"Trainer"} ,{ role: "Props", text:"Props"},
    						{ role: "RehearsalSpace", text:"Rehearsal Space"}, { role: "Audience", text:"Need Audience"}],
    				languages:["Hindi", "Kannada", "Marathi", "Tamil", "Malayalam", "Bengali", "Punjabi", "Telegu", "English"],
    				eventCategories:[{ category: "Play", text:"Play"}, { category: "Workshop", text:"Training or Workshop"}, 
    							   { category: "Storytelling", text:"Storytelling event"}, {category: "Reading", text:"Reading"},
    							   {category: "Others", text:"Other Events"}],
                    rolesForSearch: [{ role: "Actor", text:"Actor"}, { role: "Director", text:"Director"}, { role: "Playwright", text:"Playwright"},
                            { role: "Lights", text:"Lighting Designer"}, { role: "Dramaturgist", text:"Dramaturgist"},{ role: "Sound", text:"Sound Designer"},
                            { role: "Music", text:"Music Composer"},{ role: "Costume", text:"Costume Designer"}, { role: "MakeUp", text:"Make-up artist"},
                            { role: "SetDesign", text:"Set Designer"},{ role: "StageManager", text:"Production Manager"}, 
                            { role: "Backstage", text:"Backstage Support"}, { role: "Trainer", text:"Trainer"}, { role: "Audience", text:"Love to watch plays"}]
    			
                  ,  Bangluru: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru2"},{ location: "Bhopal1", text: "Bhopal1"}, { location: "Bhopal2", text: "Bhopal2"}],
                    Bhopal: [{ location: "Bhopal1", text: "Bhopal1"}, { location: "Bhopal2", text: "Bhopal2"}],
                    Chennai: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru2"}],
                    Kolkata: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru2"}],
                    Mumbai: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru2"}],
                    Pune: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru2"}],
                    Chandigarh: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru2"}],
                    Delhi: [{ location: "Bengaluru1", text: "Bengaluru1"}, { location: "Bengaluru2", text: "Bengaluru1"}],
                }
}
